#!/usr/bin/env bash
#Fixes to run nginx at port 8080
#set user in the config first line on user 
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
#replace port 80 with 8080
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
#give the  owner permissions to read and write
chmod 644 /etc/nginx/nginx.conf
#kill apache if its running the process if it is running
pkill apache2
#start the nginx service with nginx user created
sudo -u nginx service nginx start
